// Best practices content templates for the trading industry

export interface ContentTemplate {
  id: string
  category: 'compliance' | 'marketing' | 'trust' | 'educational' | 'social_media'
  subcategory: string
  title: string
  content: string
  tags: string[]
  usageHint: string
  platforms: string[]
}

export const CONTENT_TEMPLATES: ContentTemplate[] = [
  // ─── COMPLIANCE & LEGAL (15) ──────────────────────────────
  {
    id: 'comp-01', category: 'compliance', subcategory: 'risk_disclaimer',
    title: 'General Risk Disclaimer',
    content: 'Trading in financial instruments carries a high level of risk to your capital with the possibility of losing more than your initial investment. Trading is not suitable for all investors. Please ensure you fully understand the risks involved before trading.',
    tags: ['risk', 'disclaimer', 'footer', 'required'],
    usageHint: 'Place in website footer, email signatures, and social media bios',
    platforms: ['website', 'email', 'social'],
  },
  {
    id: 'comp-02', category: 'compliance', subcategory: 'risk_disclaimer',
    title: 'CFD Risk Warning',
    content: 'CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. Between 74-89% of retail investor accounts lose money when trading CFDs. You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.',
    tags: ['cfd', 'risk', 'leverage', 'esma', 'required'],
    usageHint: 'Required by ESMA regulations on all marketing materials',
    platforms: ['website', 'ads', 'social'],
  },
  {
    id: 'comp-03', category: 'compliance', subcategory: 'kyc',
    title: 'KYC Verification Notice',
    content: 'To comply with international anti-money laundering regulations, we require identity verification before you can start trading. Please have your government-issued ID and proof of address ready. Verification typically takes 1-2 business days.',
    tags: ['kyc', 'verification', 'aml', 'onboarding'],
    usageHint: 'Display during account registration and onboarding flow',
    platforms: ['website', 'email'],
  },
  {
    id: 'comp-04', category: 'compliance', subcategory: 'aml',
    title: 'AML Policy Summary',
    content: 'We are committed to preventing money laundering and terrorist financing. Our AML program includes customer due diligence, transaction monitoring, suspicious activity reporting, and ongoing staff training in compliance with international regulations.',
    tags: ['aml', 'compliance', 'policy', 'legal'],
    usageHint: 'Use on compliance page and legal documentation',
    platforms: ['website'],
  },
  {
    id: 'comp-05', category: 'compliance', subcategory: 'data_protection',
    title: 'Data Protection Notice',
    content: 'We take your privacy seriously. Your personal and financial data is encrypted using 256-bit SSL technology. We never share your information with third parties for marketing purposes. You have the right to access, correct, or delete your data at any time.',
    tags: ['gdpr', 'privacy', 'data', 'security'],
    usageHint: 'Include in privacy policy and registration forms',
    platforms: ['website', 'email'],
  },
  {
    id: 'comp-06', category: 'compliance', subcategory: 'regulatory',
    title: 'CySEC Regulation Badge Text',
    content: 'Authorized and regulated by the Cyprus Securities and Exchange Commission (CySEC) under license number XXX/XX. Client funds are held in segregated accounts with tier-1 European banks.',
    tags: ['cysec', 'regulation', 'license', 'trust'],
    usageHint: 'Display in website footer and about page',
    platforms: ['website'],
  },
  {
    id: 'comp-07', category: 'compliance', subcategory: 'regulatory',
    title: 'FCA Regulation Badge Text',
    content: 'Authorized and regulated by the Financial Conduct Authority (FCA), FRN: XXXXXX. Registered with the Financial Services Compensation Scheme (FSCS) providing protection up to GBP 85,000.',
    tags: ['fca', 'regulation', 'uk', 'fscs', 'trust'],
    usageHint: 'Display in footer for UK-targeted pages',
    platforms: ['website'],
  },
  {
    id: 'comp-08', category: 'compliance', subcategory: 'fund_safety',
    title: 'Client Fund Segregation',
    content: 'All client funds are held in segregated accounts, completely separate from company operational funds. In the unlikely event of company insolvency, client funds are protected and will be returned to clients.',
    tags: ['fund_safety', 'segregation', 'trust', 'security'],
    usageHint: 'Use on about page and security/trust sections',
    platforms: ['website'],
  },
  {
    id: 'comp-09', category: 'compliance', subcategory: 'crypto_disclaimer',
    title: 'Crypto Asset Risk Warning',
    content: 'Cryptoassets are highly volatile and unregulated in most jurisdictions. No consumer protection may apply. Tax on profits may apply. The value of your investment can go down as well as up.',
    tags: ['crypto', 'risk', 'disclaimer', 'volatile'],
    usageHint: 'Required on all crypto-related content and pages',
    platforms: ['website', 'social', 'ads'],
  },
  {
    id: 'comp-10', category: 'compliance', subcategory: 'past_performance',
    title: 'Past Performance Disclaimer',
    content: 'Past performance is not indicative of future results. Trading results shown are hypothetical and may not reflect actual trading. Simulated results do not represent actual trading and may have been over- or under-compensated for the impact of market factors.',
    tags: ['performance', 'disclaimer', 'results', 'required'],
    usageHint: 'Include wherever performance data, charts, or results are shown',
    platforms: ['website', 'social', 'ads'],
  },
  {
    id: 'comp-11', category: 'compliance', subcategory: 'leverage_warning',
    title: 'Leverage Risk Notice',
    content: 'Leverage amplifies both profits and losses. A leverage of 1:100 means a 1% market movement can result in a 100% profit or loss on your invested capital. Always use risk management tools such as stop-loss orders.',
    tags: ['leverage', 'risk', 'education', 'margin'],
    usageHint: 'Show on account types page and leverage-related content',
    platforms: ['website', 'education'],
  },
  {
    id: 'comp-12', category: 'compliance', subcategory: 'negative_balance',
    title: 'Negative Balance Protection',
    content: 'We offer negative balance protection on all retail accounts. You will never lose more than your deposited amount. If your account balance goes negative, we will reset it to zero at no cost.',
    tags: ['protection', 'negative_balance', 'retail', 'safety'],
    usageHint: 'Highlight as a key feature on account types and risk pages',
    platforms: ['website'],
  },
  {
    id: 'comp-13', category: 'compliance', subcategory: 'prop_trading',
    title: 'Prop Trading Evaluation Disclaimer',
    content: 'Challenge fees are non-refundable unless stated otherwise. Funded account profits are simulated until payout is processed. The firm reserves the right to modify challenge rules with 30 days notice. Trading is performed on demo accounts with live market data.',
    tags: ['prop', 'challenge', 'disclaimer', 'evaluation'],
    usageHint: 'Required on prop trading challenge pages and checkout',
    platforms: ['website'],
  },
  {
    id: 'comp-14', category: 'compliance', subcategory: 'advertising',
    title: 'Social Media Advertising Disclaimer',
    content: 'This is a marketing communication. It should not be taken as investment advice. Trading carries risks. Capital at risk. Not a recommendation to trade. Subject to terms and conditions.',
    tags: ['advertising', 'social', 'disclaimer', 'ads'],
    usageHint: 'Append to all paid social media advertisements',
    platforms: ['social', 'ads'],
  },
  {
    id: 'comp-15', category: 'compliance', subcategory: 'insurance',
    title: 'Investor Compensation Scheme',
    content: 'As a regulated entity, our clients are covered by the Investor Compensation Fund (ICF), which provides compensation up to EUR 20,000 in the event of the firm being unable to meet its obligations.',
    tags: ['insurance', 'icf', 'compensation', 'trust'],
    usageHint: 'Display on regulation and about pages',
    platforms: ['website'],
  },

  // ─── MARKETING COPY (20) ──────────────────────────────────
  {
    id: 'mkt-01', category: 'marketing', subcategory: 'cta',
    title: 'Open Account CTA',
    content: 'Start trading in minutes. Open your free account today and get access to 60+ currency pairs, advanced charting tools, and 24/7 support.',
    tags: ['cta', 'registration', 'conversion', 'account'],
    usageHint: 'Primary call-to-action on homepage and landing pages',
    platforms: ['website', 'ads', 'email'],
  },
  {
    id: 'mkt-02', category: 'marketing', subcategory: 'cta',
    title: 'Demo Account CTA',
    content: 'Not ready to trade live? Try our risk-free demo account with $100,000 in virtual funds. No credit card required. Practice your strategies with real market conditions.',
    tags: ['demo', 'cta', 'free', 'risk_free'],
    usageHint: 'Secondary CTA for users not ready to commit',
    platforms: ['website', 'ads', 'email'],
  },
  {
    id: 'mkt-03', category: 'marketing', subcategory: 'value_prop',
    title: 'Tight Spreads Value Prop',
    content: 'Industry-leading spreads from 0.0 pips on major currency pairs. No hidden markups, no dealing desk intervention. What you see is what you get.',
    tags: ['spreads', 'pricing', 'value', 'competitive'],
    usageHint: 'Use in feature sections and comparison pages',
    platforms: ['website', 'ads'],
  },
  {
    id: 'mkt-04', category: 'marketing', subcategory: 'value_prop',
    title: 'Fast Execution Value Prop',
    content: 'Lightning-fast execution with average fill times under 30ms. No requotes, no slippage on limit orders. Our tier-1 liquidity ensures the best available prices.',
    tags: ['execution', 'speed', 'technology', 'reliability'],
    usageHint: 'Highlight in platform and technology sections',
    platforms: ['website'],
  },
  {
    id: 'mkt-05', category: 'marketing', subcategory: 'value_prop',
    title: 'Regulation Value Prop',
    content: 'Trade with confidence. We are regulated by top-tier financial authorities and hold your funds in segregated accounts with leading European banks.',
    tags: ['regulation', 'trust', 'safety', 'confidence'],
    usageHint: 'Use in trust-building sections and ads',
    platforms: ['website', 'ads', 'social'],
  },
  {
    id: 'mkt-06', category: 'marketing', subcategory: 'urgency',
    title: 'Limited Time Bonus',
    content: 'For a limited time only: Get a 100% deposit bonus on your first deposit. Double your trading power and maximize your potential returns. Offer ends soon!',
    tags: ['bonus', 'promotion', 'urgency', 'deposit'],
    usageHint: 'Use for promotional campaigns (ensure compliance with local regulations)',
    platforms: ['website', 'email', 'social', 'ads'],
  },
  {
    id: 'mkt-07', category: 'marketing', subcategory: 'social_proof',
    title: 'Trader Count Social Proof',
    content: 'Join over 500,000 traders worldwide who trust us with their investments. Rated 4.5/5 on Trustpilot with 10,000+ reviews.',
    tags: ['social_proof', 'trust', 'reviews', 'numbers'],
    usageHint: 'Display near CTAs and on homepage hero section',
    platforms: ['website', 'ads'],
  },
  {
    id: 'mkt-08', category: 'marketing', subcategory: 'feature',
    title: 'Mobile Trading Feature',
    content: 'Trade anytime, anywhere. Our award-winning mobile app puts the power of the markets in your pocket. Real-time quotes, advanced charts, and one-tap trading.',
    tags: ['mobile', 'app', 'feature', 'convenience'],
    usageHint: 'Promote mobile app in feature sections and app store descriptions',
    platforms: ['website', 'social', 'ads'],
  },
  {
    id: 'mkt-09', category: 'marketing', subcategory: 'feature',
    title: 'Copy Trading Feature',
    content: 'New to trading? Copy the strategies of successful traders with one click. Browse top performers, allocate funds, and automatically mirror their trades in real-time.',
    tags: ['copy_trading', 'social_trading', 'beginners', 'feature'],
    usageHint: 'Feature on copy trading page and beginner-targeted content',
    platforms: ['website', 'social', 'ads'],
  },
  {
    id: 'mkt-10', category: 'marketing', subcategory: 'email',
    title: 'Welcome Email Subject Lines',
    content: 'Welcome to [Brand] — Your Trading Journey Starts Now | Your account is ready — here\'s what to do next | [Brand]: Start trading with $100,000 demo funds today',
    tags: ['email', 'subject_line', 'welcome', 'onboarding'],
    usageHint: 'Use for welcome email sequence subject lines (pick one)',
    platforms: ['email'],
  },
  {
    id: 'mkt-11', category: 'marketing', subcategory: 'feature',
    title: '24/7 Support Feature',
    content: 'Our dedicated support team is available around the clock, 7 days a week. Whether you prefer live chat, email, or phone, help is always just a click away.',
    tags: ['support', 'customer_service', 'feature', 'availability'],
    usageHint: 'Include in feature lists and contact page',
    platforms: ['website'],
  },
  {
    id: 'mkt-12', category: 'marketing', subcategory: 'prop_trading',
    title: 'Prop Firm Challenge CTA',
    content: 'Prove your skills, get funded. Pass our evaluation challenge and trade with up to $200,000 in capital. Keep up to 90% of the profits you generate.',
    tags: ['prop', 'challenge', 'funded', 'cta'],
    usageHint: 'Primary CTA for prop trading firm pages',
    platforms: ['website', 'ads', 'social'],
  },
  {
    id: 'mkt-13', category: 'marketing', subcategory: 'prop_trading',
    title: 'Payout Proof Social Proof',
    content: 'We have paid out over $10 million to our funded traders. Real payouts, real traders, verified results. Join the community of successful funded traders.',
    tags: ['prop', 'payouts', 'proof', 'social_proof'],
    usageHint: 'Show on homepage and payout proof pages',
    platforms: ['website', 'social'],
  },
  {
    id: 'mkt-14', category: 'marketing', subcategory: 'crypto',
    title: 'Crypto Exchange CTA',
    content: 'Buy, sell, and trade 200+ cryptocurrencies with low fees and institutional-grade security. Create your free account in 2 minutes.',
    tags: ['crypto', 'exchange', 'cta', 'registration'],
    usageHint: 'Primary CTA for crypto exchange websites',
    platforms: ['website', 'ads'],
  },
  {
    id: 'mkt-15', category: 'marketing', subcategory: 'crypto',
    title: 'Staking Promotion',
    content: 'Earn passive income on your crypto. Stake your assets and earn up to 14% APY. No minimum holding period with flexible staking. Start earning today.',
    tags: ['staking', 'earn', 'passive_income', 'crypto'],
    usageHint: 'Promote staking features and DeFi products',
    platforms: ['website', 'social', 'email'],
  },
  {
    id: 'mkt-16', category: 'marketing', subcategory: 'retargeting',
    title: 'Abandoned Registration Reminder',
    content: 'You\'re almost there! Complete your registration and start trading in minutes. Your free account comes with $100K demo funds and access to 200+ instruments.',
    tags: ['retargeting', 'abandoned', 'registration', 'email'],
    usageHint: 'Send to users who started but did not complete registration',
    platforms: ['email', 'ads'],
  },
  {
    id: 'mkt-17', category: 'marketing', subcategory: 'referral',
    title: 'Refer a Friend Program',
    content: 'Earn rewards for every friend you refer. When your friend opens and funds an account, you both receive a bonus. No limit on referrals.',
    tags: ['referral', 'bonus', 'program', 'growth'],
    usageHint: 'Promote in email campaigns and dedicated referral page',
    platforms: ['website', 'email', 'social'],
  },
  {
    id: 'mkt-18', category: 'marketing', subcategory: 'seasonal',
    title: 'Year-End Campaign',
    content: 'Start the new year with a fresh trading strategy. Open your account before December 31st and receive exclusive bonuses plus a free trading masterclass.',
    tags: ['seasonal', 'campaign', 'year_end', 'promotion'],
    usageHint: 'Use for end-of-year promotional campaigns',
    platforms: ['email', 'social', 'ads'],
  },
  {
    id: 'mkt-19', category: 'marketing', subcategory: 'partnership',
    title: 'IB/Affiliate Program Pitch',
    content: 'Partner with us and earn up to $15 per lot. High conversion rates, dedicated account manager, real-time tracking, and flexible payment options. Join 5,000+ active partners.',
    tags: ['ib', 'affiliate', 'partnership', 'revenue'],
    usageHint: 'Use on affiliate/partner recruitment pages',
    platforms: ['website', 'email'],
  },
  {
    id: 'mkt-20', category: 'marketing', subcategory: 'headline',
    title: 'Power Headlines Collection',
    content: 'Trade the World\'s Markets | Your Gateway to Global Finance | Smart Trading Starts Here | Trade with the Best | Where Traders Become Winners',
    tags: ['headlines', 'hero', 'homepage', 'ads'],
    usageHint: 'A/B test these as homepage hero headlines or ad copy',
    platforms: ['website', 'ads'],
  },

  // ─── TRUST & CREDIBILITY (15) ─────────────────────────────
  {
    id: 'trust-01', category: 'trust', subcategory: 'testimonial',
    title: 'Trader Testimonial Template',
    content: '"I\'ve been trading with [Brand] for 2 years now. The spreads are consistently tight, execution is fast, and their support team is incredibly responsive. Highly recommended for serious traders." — John D., Professional Trader',
    tags: ['testimonial', 'review', 'social_proof', 'trust'],
    usageHint: 'Template for collecting and displaying trader testimonials',
    platforms: ['website'],
  },
  {
    id: 'trust-02', category: 'trust', subcategory: 'awards',
    title: 'Awards Section Template',
    content: 'Recognized by the industry: Best Forex Broker 2024 (Finance Magnates), Most Trusted Broker (Global Brands Magazine), Best Trading Platform (World Finance Awards).',
    tags: ['awards', 'recognition', 'trust', 'credibility'],
    usageHint: 'Display in an awards ribbon/bar section on homepage and about page',
    platforms: ['website'],
  },
  {
    id: 'trust-03', category: 'trust', subcategory: 'security',
    title: 'Platform Security Highlights',
    content: '256-bit SSL encryption on all connections. Two-factor authentication (2FA) for account access. DDoS protection and 99.99% uptime guarantee. Regular third-party security audits.',
    tags: ['security', 'ssl', '2fa', 'technology', 'trust'],
    usageHint: 'Display in security section and footer trust badges area',
    platforms: ['website'],
  },
  {
    id: 'trust-04', category: 'trust', subcategory: 'statistics',
    title: 'Key Statistics Display',
    content: '$2.5B+ daily trading volume | 500,000+ registered accounts | 60+ currency pairs | 24/7 customer support | 15+ years of experience',
    tags: ['statistics', 'numbers', 'trust', 'social_proof'],
    usageHint: 'Show as a stats bar on homepage or about page',
    platforms: ['website'],
  },
  {
    id: 'trust-05', category: 'trust', subcategory: 'partnership',
    title: 'Liquidity Provider Partners',
    content: 'We partner with the world\'s leading liquidity providers to ensure deep market depth and the best available pricing. Our ECN network aggregates prices from 20+ tier-1 banks.',
    tags: ['liquidity', 'ecn', 'partners', 'technology'],
    usageHint: 'Show on pricing page and about/technology sections',
    platforms: ['website'],
  },
  {
    id: 'trust-06', category: 'trust', subcategory: 'payment',
    title: 'Payment Methods Section',
    content: 'Fast and secure deposits & withdrawals. We accept Visa, Mastercard, bank wire, Skrill, Neteller, and cryptocurrency. No deposit fees. Withdrawals processed within 24 hours.',
    tags: ['payments', 'deposit', 'withdrawal', 'convenience'],
    usageHint: 'Display on deposit page and in footer payment icons section',
    platforms: ['website'],
  },
  {
    id: 'trust-07', category: 'trust', subcategory: 'uptime',
    title: 'Reliability & Uptime',
    content: 'Our trading infrastructure is hosted in Equinix data centers with 99.99% uptime. Multiple redundant connections ensure you never miss a trading opportunity.',
    tags: ['uptime', 'reliability', 'infrastructure', 'technology'],
    usageHint: 'Include on technology/platform pages',
    platforms: ['website'],
  },
  {
    id: 'trust-08', category: 'trust', subcategory: 'team',
    title: 'Leadership Team Bio Template',
    content: '[Name], [Title]. With [X] years of experience in financial services, [Name] leads our [department]. Previously at [Company], [Name] brings deep expertise in [area]. [Degree] from [University].',
    tags: ['team', 'bio', 'leadership', 'about'],
    usageHint: 'Template for team member bios on about page',
    platforms: ['website'],
  },
  {
    id: 'trust-09', category: 'trust', subcategory: 'guarantee',
    title: 'Satisfaction Guarantee',
    content: 'Not satisfied? We offer a 30-day money-back guarantee on all challenge fees. If you feel our platform doesn\'t meet your expectations, request a full refund — no questions asked.',
    tags: ['guarantee', 'refund', 'trust', 'prop_trading'],
    usageHint: 'Display near pricing and checkout for prop trading firms',
    platforms: ['website'],
  },
  {
    id: 'trust-10', category: 'trust', subcategory: 'compliance_badge',
    title: 'Multi-Regulation Trust Bar',
    content: 'Regulated globally: CySEC (EU) | FCA (UK) | ASIC (Australia) | FSA (Seychelles). Multi-jurisdictional compliance ensures the highest standards of investor protection.',
    tags: ['regulation', 'multi_jurisdiction', 'trust', 'global'],
    usageHint: 'Display as a trust bar across the website footer',
    platforms: ['website'],
  },
  {
    id: 'trust-11', category: 'trust', subcategory: 'social_proof',
    title: 'Trustpilot Review Widget Text',
    content: 'Rated Excellent on Trustpilot. Read what our traders are saying about their experience. 4.5 out of 5 based on 10,000+ verified reviews.',
    tags: ['trustpilot', 'reviews', 'rating', 'social_proof'],
    usageHint: 'Place near CTAs and on homepage',
    platforms: ['website'],
  },
  {
    id: 'trust-12', category: 'trust', subcategory: 'technology',
    title: 'Technology Stack Highlights',
    content: 'Built on enterprise-grade technology: AWS cloud infrastructure, Cloudflare DDoS protection, real-time market data feeds, and millisecond-precision order execution.',
    tags: ['technology', 'infrastructure', 'speed', 'reliability'],
    usageHint: 'Showcase on technology page and for B2B/white-label sections',
    platforms: ['website'],
  },
  {
    id: 'trust-13', category: 'trust', subcategory: 'education',
    title: 'Free Education Promise',
    content: 'We believe every trader deserves access to quality education. That\'s why our complete trading academy, including webinars, courses, and daily analysis, is completely free for all account holders.',
    tags: ['education', 'free', 'value', 'commitment'],
    usageHint: 'Highlight on education page and marketing materials',
    platforms: ['website', 'social'],
  },
  {
    id: 'trust-14', category: 'trust', subcategory: 'payout',
    title: 'Fast Payout Guarantee',
    content: 'We process all withdrawal requests within 24 hours. Most e-wallet withdrawals are instant. Bank wire transfers are completed within 1-3 business days.',
    tags: ['payout', 'withdrawal', 'speed', 'trust'],
    usageHint: 'Feature on payments page and FAQ',
    platforms: ['website'],
  },
  {
    id: 'trust-15', category: 'trust', subcategory: 'community',
    title: 'Active Community Stats',
    content: 'Join our thriving community: 50,000+ Discord members, 100,000+ Telegram subscribers, and daily live trading rooms. Learn, share, and grow together.',
    tags: ['community', 'social', 'engagement', 'growth'],
    usageHint: 'Promote on about page and social media sections',
    platforms: ['website', 'social'],
  },

  // ─── EDUCATIONAL (15) ─────────────────────────────────────
  {
    id: 'edu-01', category: 'educational', subcategory: 'beginner',
    title: 'What is Forex Trading?',
    content: 'Forex (foreign exchange) is the global marketplace for buying and selling currencies. With a daily trading volume of over $6 trillion, it is the largest financial market in the world. Traders speculate on whether a currency will strengthen or weaken against another.',
    tags: ['forex', 'basics', 'beginner', 'definition'],
    usageHint: 'Use as introductory content on education page',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-02', category: 'educational', subcategory: 'beginner',
    title: 'Understanding Pips and Lots',
    content: 'A pip is the smallest price movement in a currency pair, typically 0.0001 for most pairs. A standard lot is 100,000 units of the base currency. Mini lots (10,000) and micro lots (1,000) allow traders to start with smaller positions.',
    tags: ['pips', 'lots', 'basics', 'terminology'],
    usageHint: 'Include in trading glossary and beginner education',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-03', category: 'educational', subcategory: 'risk_management',
    title: 'The 1% Risk Rule',
    content: 'Professional traders never risk more than 1-2% of their account balance on a single trade. This means with a $10,000 account, your maximum risk per trade should be $100-$200. This simple rule is the foundation of long-term trading success.',
    tags: ['risk_management', 'position_sizing', 'rule', 'professional'],
    usageHint: 'Share as educational content on social media and education page',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-04', category: 'educational', subcategory: 'technical',
    title: 'Support and Resistance Explained',
    content: 'Support levels are prices where buying pressure historically exceeds selling pressure, preventing further decline. Resistance levels are where selling pressure exceeds buying. These levels are among the most important concepts in technical analysis.',
    tags: ['technical_analysis', 'support', 'resistance', 'chart'],
    usageHint: 'Use in technical analysis education section',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-05', category: 'educational', subcategory: 'technical',
    title: 'Candlestick Patterns Intro',
    content: 'Candlestick charts display four key prices: open, high, low, and close. Common bullish patterns include the hammer, morning star, and engulfing pattern. Bearish patterns include the shooting star, evening star, and dark cloud cover.',
    tags: ['candlestick', 'patterns', 'charting', 'technical'],
    usageHint: 'Create visual content for social media and education page',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-06', category: 'educational', subcategory: 'fundamental',
    title: 'Economic Calendar Importance',
    content: 'The economic calendar tracks key data releases that move markets: Non-Farm Payrolls (NFP), GDP, CPI inflation, interest rate decisions, and PMI data. Always check the calendar before placing trades to avoid unexpected volatility.',
    tags: ['economic_calendar', 'fundamental', 'news', 'data'],
    usageHint: 'Share before major economic events on social media',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-07', category: 'educational', subcategory: 'psychology',
    title: 'Trading Psychology Basics',
    content: 'The two most dangerous emotions in trading are fear and greed. Fear causes traders to exit winning trades too early or avoid valid setups. Greed leads to over-leveraging and holding losers too long. Develop a trading plan and stick to it.',
    tags: ['psychology', 'mindset', 'emotions', 'discipline'],
    usageHint: 'Great for social media educational series',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-08', category: 'educational', subcategory: 'strategy',
    title: 'Trend Following Strategy',
    content: 'The trend is your friend. Use moving averages (50 and 200 period) to identify the direction. Trade in the direction of the trend using pullbacks to key support/resistance levels. Set your stop-loss below the previous swing low (for longs).',
    tags: ['strategy', 'trend', 'moving_averages', 'trading_plan'],
    usageHint: 'Feature in education section and strategy guides',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-09', category: 'educational', subcategory: 'crypto',
    title: 'What is Blockchain?',
    content: 'Blockchain is a decentralized digital ledger that records transactions across a network of computers. Each block contains a set of transactions and is cryptographically linked to the previous block, creating an immutable chain of records.',
    tags: ['blockchain', 'crypto', 'basics', 'technology'],
    usageHint: 'Introductory content for crypto education section',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-10', category: 'educational', subcategory: 'crypto',
    title: 'DeFi Explained Simply',
    content: 'DeFi (Decentralized Finance) recreates traditional financial services on the blockchain without intermediaries. It enables lending, borrowing, trading, and earning interest through smart contracts, giving users full control of their assets.',
    tags: ['defi', 'crypto', 'smart_contracts', 'lending'],
    usageHint: 'Education content for crypto exchange websites',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-11', category: 'educational', subcategory: 'prop_trading',
    title: 'How Prop Trading Works',
    content: 'Prop trading firms provide capital to skilled traders. You prove your ability through an evaluation challenge with specific profit targets and risk rules. Once funded, you trade with the firm\'s capital and keep 70-90% of the profits.',
    tags: ['prop_trading', 'funded', 'challenge', 'basics'],
    usageHint: 'Introductory content on prop firm education page',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-12', category: 'educational', subcategory: 'prop_trading',
    title: 'Passing Your Prop Challenge',
    content: 'Tips for passing a prop firm challenge: Trade only A+ setups, use proper position sizing (0.5-1% risk per trade), avoid overtrading, respect the daily drawdown limit, and trade during high-volume sessions for better fills.',
    tags: ['prop_trading', 'tips', 'challenge', 'strategy'],
    usageHint: 'Share as educational content on blog and social media',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-13', category: 'educational', subcategory: 'risk_management',
    title: 'Stop-Loss Placement Guide',
    content: 'Place stop-losses at technical levels, not arbitrary pip distances. For buy trades: below key support or the previous swing low. For sell trades: above resistance or the previous swing high. Never move your stop-loss further away from entry.',
    tags: ['stop_loss', 'risk_management', 'technical', 'placement'],
    usageHint: 'Educational content for all trading niches',
    platforms: ['website', 'social'],
  },
  {
    id: 'edu-14', category: 'educational', subcategory: 'glossary',
    title: 'Essential Trading Terms',
    content: 'Spread: difference between bid/ask. Leverage: borrowed capital for larger positions. Margin: required deposit to open a position. Pip: smallest price movement. Lot: standard unit of measurement. Stop-loss: automatic exit at a set price.',
    tags: ['glossary', 'terminology', 'basics', 'reference'],
    usageHint: 'Use as a quick reference card or glossary page',
    platforms: ['website'],
  },
  {
    id: 'edu-15', category: 'educational', subcategory: 'market_hours',
    title: 'Forex Market Sessions',
    content: 'The forex market is open 24/5 across 4 major sessions: Sydney (10pm-7am GMT), Tokyo (12am-9am), London (8am-5pm), and New York (1pm-10pm). The London-New York overlap (1pm-5pm GMT) typically sees the highest volume and volatility.',
    tags: ['market_hours', 'sessions', 'liquidity', 'timing'],
    usageHint: 'Create a visual session chart for website and social media',
    platforms: ['website', 'social'],
  },

  // ─── SOCIAL MEDIA (15) ────────────────────────────────────
  {
    id: 'social-01', category: 'social_media', subcategory: 'instagram',
    title: 'Instagram Bio Template',
    content: '[Brand] | [Tagline]\nTrade Forex | Crypto | CFDs\nSpreads from 0.0 pips\nRegulated & Trusted\nStart trading: link below',
    tags: ['instagram', 'bio', 'profile', 'template'],
    usageHint: 'Customize and use as Instagram bio',
    platforms: ['instagram'],
  },
  {
    id: 'social-02', category: 'social_media', subcategory: 'twitter',
    title: 'Twitter Bio Template',
    content: '[Brand] — Your trusted trading partner. Trade Forex, Crypto & CFDs with tight spreads and fast execution. Regulated broker. #forex #trading',
    tags: ['twitter', 'bio', 'profile', 'template'],
    usageHint: 'Customize and use as Twitter/X bio',
    platforms: ['twitter'],
  },
  {
    id: 'social-03', category: 'social_media', subcategory: 'linkedin',
    title: 'LinkedIn Company Description',
    content: '[Brand] is a regulated financial services company specializing in online trading solutions. We provide access to global markets through our advanced trading platforms, offering competitive spreads and professional-grade tools to traders worldwide.',
    tags: ['linkedin', 'company', 'description', 'professional'],
    usageHint: 'Use as LinkedIn company page description',
    platforms: ['linkedin'],
  },
  {
    id: 'social-04', category: 'social_media', subcategory: 'hashtags',
    title: 'Forex Hashtag Set',
    content: '#forex #forextrading #forextrader #forexmarket #forexsignals #forexlife #forexeducation #forexanalysis #forexnews #currencytrading #daytrading #swingtrading #technicalanalysis #priceaction #tradinglife',
    tags: ['hashtags', 'forex', 'instagram', 'reach'],
    usageHint: 'Use with forex-related posts on Instagram and Twitter',
    platforms: ['instagram', 'twitter'],
  },
  {
    id: 'social-05', category: 'social_media', subcategory: 'hashtags',
    title: 'Crypto Hashtag Set',
    content: '#crypto #cryptocurrency #bitcoin #ethereum #blockchain #defi #web3 #cryptotrading #altcoins #hodl #nft #cryptonews #btc #eth #cryptomarket',
    tags: ['hashtags', 'crypto', 'instagram', 'reach'],
    usageHint: 'Use with crypto-related posts on Instagram and Twitter',
    platforms: ['instagram', 'twitter'],
  },
  {
    id: 'social-06', category: 'social_media', subcategory: 'engagement',
    title: 'Monday Market Open Hook',
    content: 'Markets are open! What are you watching this week? Drop your top 3 pairs/assets in the comments below.',
    tags: ['engagement', 'monday', 'interactive', 'comments'],
    usageHint: 'Post every Monday morning to boost engagement',
    platforms: ['instagram', 'twitter', 'facebook', 'linkedin'],
  },
  {
    id: 'social-07', category: 'social_media', subcategory: 'engagement',
    title: 'Friday Wrap-Up Hook',
    content: 'How was your trading week? Share your best trade in the comments. Remember: consistency beats intensity. Have a great weekend, traders!',
    tags: ['engagement', 'friday', 'interactive', 'community'],
    usageHint: 'Post every Friday to build community engagement',
    platforms: ['instagram', 'twitter', 'facebook'],
  },
  {
    id: 'social-08', category: 'social_media', subcategory: 'story',
    title: 'Instagram Story Poll Templates',
    content: 'Which market will perform best this week? A) Forex B) Crypto | EUR/USD this week: Bullish or Bearish? | What\'s your trading style? A) Scalper B) Day Trader C) Swing D) Position',
    tags: ['story', 'poll', 'interactive', 'instagram'],
    usageHint: 'Use for Instagram Stories polls to boost engagement',
    platforms: ['instagram'],
  },
  {
    id: 'social-09', category: 'social_media', subcategory: 'video',
    title: 'TikTok Video Hook Templates',
    content: 'POV: You just found the best entry on EUR/USD | Most traders lose money because of this one mistake... | I made $X in one trade — here\'s what happened | 3 things I wish I knew before I started trading',
    tags: ['tiktok', 'hooks', 'video', 'viral'],
    usageHint: 'Use as opening hooks for TikTok/Reels trading content',
    platforms: ['tiktok', 'instagram'],
  },
  {
    id: 'social-10', category: 'social_media', subcategory: 'telegram',
    title: 'Telegram Channel Description',
    content: 'Welcome to [Brand] Official Channel! Get daily market analysis, trading signals, exclusive promotions, and educational content. Trade with confidence.',
    tags: ['telegram', 'channel', 'description', 'template'],
    usageHint: 'Use as Telegram channel description',
    platforms: ['telegram'],
  },
  {
    id: 'social-11', category: 'social_media', subcategory: 'carousel',
    title: 'Educational Carousel Template (5 slides)',
    content: 'Slide 1: [Bold Question/Hook] | Slide 2: The Problem — [Pain point] | Slide 3: The Solution — [Key concept] | Slide 4: How to Apply It — [Actionable tips] | Slide 5: CTA — Save this for later & follow for more trading tips',
    tags: ['carousel', 'template', 'educational', 'structure'],
    usageHint: 'Use this structure for Instagram/LinkedIn educational carousels',
    platforms: ['instagram', 'linkedin'],
  },
  {
    id: 'social-12', category: 'social_media', subcategory: 'youtube',
    title: 'YouTube Video Description Template',
    content: 'In this video, we cover [topic]. Timestamps: 0:00 Intro | 1:00 [Section 1] | 3:00 [Section 2] | 5:00 [Section 3] | 7:00 Summary. Open a free account: [link]. Risk warning: Trading involves risk.',
    tags: ['youtube', 'description', 'template', 'seo'],
    usageHint: 'Template for YouTube video descriptions with SEO optimization',
    platforms: ['youtube'],
  },
  {
    id: 'social-13', category: 'social_media', subcategory: 'engagement',
    title: 'Quiz/Trivia Post Template',
    content: 'TRADING QUIZ: What does a "doji" candlestick indicate? A) Strong bullish move B) Strong bearish move C) Market indecision D) Trend reversal. Comment your answer below!',
    tags: ['quiz', 'engagement', 'educational', 'interactive'],
    usageHint: 'Post quizzes 2-3 times per week to boost engagement',
    platforms: ['instagram', 'facebook', 'twitter'],
  },
  {
    id: 'social-14', category: 'social_media', subcategory: 'content_calendar',
    title: 'Weekly Content Calendar Template',
    content: 'Monday: Market Outlook | Tuesday: Educational Tip | Wednesday: Market Analysis | Thursday: Product Spotlight | Friday: Week in Review | Saturday: Motivational | Sunday: Trading Quiz',
    tags: ['calendar', 'planning', 'schedule', 'content'],
    usageHint: 'Use as a weekly content rotation schedule',
    platforms: ['all'],
  },
  {
    id: 'social-15', category: 'social_media', subcategory: 'thread',
    title: 'Twitter Thread Starter Template',
    content: 'A thread on [topic] that every trader should know. Here\'s what I\'ve learned after [X] years of trading. [1/10] Start with a hook that creates curiosity and promises value by the end of the thread.',
    tags: ['twitter', 'thread', 'educational', 'template'],
    usageHint: 'Use to structure Twitter/X threads for educational content',
    platforms: ['twitter'],
  },
]

export function getTemplatesByCategory(category: string): ContentTemplate[] {
  return CONTENT_TEMPLATES.filter((t) => t.category === category)
}

export function getTemplatesByTags(tags: string[]): ContentTemplate[] {
  return CONTENT_TEMPLATES.filter((t) => t.tags.some((tag) => tags.includes(tag)))
}

export function getTemplatesForNiche(niche: string): ContentTemplate[] {
  const nicheKeywords: Record<string, string[]> = {
    forex_broker: ['forex', 'cfd', 'spreads', 'leverage', 'broker', 'regulation'],
    crypto_exchange: ['crypto', 'blockchain', 'defi', 'staking', 'exchange', 'bitcoin'],
    prop_trading: ['prop', 'challenge', 'funded', 'prop_trading', 'evaluation'],
  }

  const keywords = nicheKeywords[niche] || []
  if (!keywords.length) return CONTENT_TEMPLATES

  // Return all general templates + niche-specific ones
  return CONTENT_TEMPLATES.filter((t) => {
    // Always include compliance, trust, and general marketing
    if (t.category === 'compliance' || t.category === 'trust') return true
    // Filter educational and social_media by niche relevance
    return t.tags.some((tag) => keywords.includes(tag)) || !t.tags.some((tag) => ['forex', 'crypto', 'prop', 'prop_trading'].includes(tag))
  })
}
